Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 597, in <module>
    main()
  File "/usr/lib/python3.8/site.py", line 583, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.8/site.py", line 322, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/usr/lib/python3.8/site.py", line 214, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.8/site.py", line 175, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/usr/lib/python3.8/contextlib.py", line 5, in <module>
    from collections import deque
  File "/usr/lib/python3.8/collections/__init__.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
KeyboardInterrupt
